[build]
    publish = "."
    command = "rm -rf .cache && echo 'Build complete - cache cleared - $(date)' && echo 'Force cache bust'"
    ignore = "false"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    X-Accel-Expires = "0"
    Surrogate-Control = "no-store"
    Vary = "*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/register"
  to = "/register/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200
  force = true

# Catch-all rule must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Referrer-Policy = "strict-origin-when-cross-origin"