[build]
  publish = "."
  command = "echo 'Build complete - $(date)'"
  environment = { NODE_VERSION = "18" }

[build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200
  force = true

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200
  force = true

# Catch-all rule must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Referrer-Policy = "strict-origin-when-cross-origin"